# Project 3

In this project, you will perform a logistic regression on the admissions data we've been working with in projects 1 and 2.

In [16]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np

In [17]:
df_raw = pd.read_csv("../assets/admissions.csv")
df = df_raw.dropna() 
df.head()

admit    gre   gpa  prestige
0      0  380.0  3.61       3.0
1      1  660.0  3.67       3.0
2      1  800.0  4.00       1.0
3      1  640.0  3.19       4.0
4      0  520.0  2.93       4.0

## Part 1. Frequency Tables

#### 1. Let's create a frequency table of our variables

In [18]:
# frequency table for prestige and whether or not someone was admitted
pd.crosstab(df["admit"],df["prestige"])

prestige  1.0  2.0  3.0  4.0
admit                       
0          28   95   93   55
1          33   53   28   12

## Part 2. Return of dummy variables

#### 2.1 Create class or dummy variables for prestige 

In [19]:
# pd.get_dummies(df['prestige'],'pres')
df = df.join(pd.get_dummies(df['prestige'],prefix='pres'))
df.head()

admit    gre   gpa  prestige  pres_1.0  pres_2.0  pres_3.0  pres_4.0
0      0  380.0  3.61       3.0       0.0       0.0       1.0       0.0
1      1  660.0  3.67       3.0       0.0       0.0       1.0       0.0
2      1  800.0  4.00       1.0       1.0       0.0       0.0       0.0
3      1  640.0  3.19       4.0       0.0       0.0       0.0       1.0
4      0  520.0  2.93       4.0       0.0       0.0       0.0       1.0

#### 2.2 When modeling our class variables, how many do we need? 



Answer: I think you're referring to the dummy variables?  3 out of the 4.

## Part 3. Hand calculating odds ratios

Develop your intuition about expected outcomes by hand calculating odds ratios.

In [20]:
df_handcalc = df.ix[:,:-1]
print (df_handcalc.head())

   admit    gre   gpa  prestige  pres_1.0  pres_2.0  pres_3.0
0      0  380.0  3.61       3.0       0.0       0.0       1.0
1      1  660.0  3.67       3.0       0.0       0.0       1.0
2      1  800.0  4.00       1.0       1.0       0.0       0.0
3      1  640.0  3.19       4.0       0.0       0.0       0.0
4      0  520.0  2.93       4.0       0.0       0.0       0.0


In [21]:
cols_to_keep = ['admit', 'gre', 'gpa','pres_1.0','pres_2.0','pres_3.0']
df_handcalc = df[cols_to_keep]
print (df_handcalc.head())

   admit    gre   gpa  pres_1.0  pres_2.0  pres_3.0
0      0  380.0  3.61       0.0       0.0       1.0
1      1  660.0  3.67       0.0       0.0       1.0
2      1  800.0  4.00       1.0       0.0       0.0
3      1  640.0  3.19       0.0       0.0       0.0
4      0  520.0  2.93       0.0       0.0       0.0


In [22]:
#crosstab prestige 1 admission 
# frequency table cutting prestige and whether or not someone was admitted
pd.crosstab(df['admit'],df['pres_1.0']).T  # .T just transposes the crosstab

admit       0   1
pres_1.0         
0.0       243  93
1.0        28  33

In [23]:
type(pd.crosstab(df['admit'],df['pres_1.0']).T)

pandas.core.frame.DataFrame

#### 3.1 Use the cross tab above to calculate the odds of being admitted to grad school if you attended a #1 ranked college

In [24]:
odds_calc = pd.crosstab(df['admit'],df['pres_1.0']).T
print (str(odds_calc[1][1]) + ":" + str(odds_calc[0][1]))

33:28


#### 3.2 Now calculate the odds of admission if you did not attend a #1 ranked college

In [25]:
odds_calc = pd.crosstab(df['admit'],df['pres_1.0']).T
print (str(odds_calc[1][0]) + ":" + str(odds_calc[0][0]))

93:243


#### 3.3 Calculate the odds ratio

In [26]:
# odds ratio of being admitted
(243 * 33) / (93 * 28)

3.0794930875576036

#### 3.4 Write this finding in a sentenance: 

Answer: Odds are over 3 times greater of admitance if someone is from a prestige1 university

#### 3.5 Print the cross tab for prestige_4

In [27]:
pd.crosstab(df['admit'],df['pres_4.0']).T

admit       0    1
pres_4.0          
0.0       216  114
1.0        55   12

#### 3.6 Calculate the OR 

In [28]:
(216 * 12) / (114 * 55)

0.4133971291866029

#### 3.7 Write this finding in a sentence

Answer: Odds are reduced to just over 40% of the admitance rate if someone was not from a prestige4 university

## Part 4. Analysis

In [29]:
# create a clean data frame for the regression
# cols_to_keep = ['admit', 'gre', 'gpa']
# data = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_2':])
# print (data.head())

In [30]:
cols_to_keep = ['admit', 'gre', 'gpa']
data = df[cols_to_keep].join(pd.get_dummies(df['prestige'],prefix='pres2'))
data.head()

admit    gre   gpa  pres2_1.0  pres2_2.0  pres2_3.0  pres2_4.0
0      0  380.0  3.61        0.0        0.0        1.0        0.0
1      1  660.0  3.67        0.0        0.0        1.0        0.0
2      1  800.0  4.00        1.0        0.0        0.0        0.0
3      1  640.0  3.19        0.0        0.0        0.0        1.0
4      0  520.0  2.93        0.0        0.0        0.0        1.0

In [31]:
data = data.ix[:,0:-1]
data.head(3)

admit    gre   gpa  pres2_1.0  pres2_2.0  pres2_3.0
0      0  380.0  3.61        0.0        0.0        1.0
1      1  660.0  3.67        0.0        0.0        1.0
2      1  800.0  4.00        1.0        0.0        0.0

We're going to add a constant term for our Logistic Regression. The statsmodels function we're going to be using requires that intercepts/constants are specified explicitly.

In [32]:
# manually add the intercept
data['intercept'] = 1.0
data.head(3)

admit    gre   gpa  pres2_1.0  pres2_2.0  pres2_3.0  intercept
0      0  380.0  3.61        0.0        0.0        1.0        1.0
1      1  660.0  3.67        0.0        0.0        1.0        1.0
2      1  800.0  4.00        1.0        0.0        0.0        1.0

#### 4.1 Set the covariates to a variable called train_cols

In [33]:
train_cols = data[['gre', 'gpa', 'pres2_1.0', 'pres2_2.0', 'pres2_3.0']]
train_cols.head(2)

gre   gpa  pres2_1.0  pres2_2.0  pres2_3.0
0  380.0  3.61        0.0        0.0        1.0
1  660.0  3.67        0.0        0.0        1.0

#### 4.2 Fit the model

In [41]:
import sklearn.linear_model as lm

from sklearn import grid_search, cross_validation
from sklearn.linear_model import LogisticRegression

In [42]:
model = lm.LogisticRegression()

In [43]:
model.fit(train_cols, data.admit)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

#### 4.3 Print the summary results

In [44]:
# pres2 = [i for i in data.columns if 'pres2_' in i]
model.predict(train_cols)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [46]:
from sklearn import grid_search, cross_validation
from sklearn.linear_model import LogisticRegression

#### 4.4 Calculate the odds ratios of the coeffiencents and their 95% CI intervals

hint 1: np.exp(X)

hint 2: conf['OR'] = params
        
           conf.columns = ['2.5%', '97.5%', 'OR']

In [47]:
# not sure how best to do this using sklearn, so using statsmodel instead
# Statsmodels logistic regression is sm.Logit
import statsmodels.api as sm

In [56]:
lm = sm.Logit(data.admit, train_cols)
lm.fit()
result = lm.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.605465
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.605465
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  admit   No. Observations:                  397
Model:                          Logit   Df Residuals:                      392
Method:                           MLE   Df Model:                            4
Date:                Sun, 18 Dec 2016   Pseudo R-squ.:                 0.03107
Time:                        23:52:36   Log-Likelihood:                -240.37
converged:                       True   LL-Null:                       -248.08
                                        LLR p-value:                  0.003913
==============================================================================
                 coef    std err          z      P>|z|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
gre            0.0011      0.001      1.043      0.297        -0.001     0.003
gpa           -0.5162      0.192     -2.682      0.007        -0.893    -0.139
pres2_1.0      1.2948      0.385      3.361      0.001         0.540     2.050
pres2_2.0      0.5120      0.327      1.567      0.117        -0.129     1.153
pres2_3.0     -0.0504      0.354     -0.142      0.887        -0.745     0.644
==============================================================================
"""

In [57]:
np.exp(result.params)

gre          1.001069
gpa          0.596794
pres2_1.0    3.650274
pres2_2.0    1.668639
pres2_3.0    0.950821
dtype: float64

#### 4.5 Interpret the OR of Prestige_2

In [ ]:
# OR = Odds Ratio.

Answer: Having a prestige value of 2 increases odds of admission by 1.67x

#### 4.6 Interpret the OR of GPA

Answer: Increase of GPA by 1 decreases odds of addmission by 60%

## Part 5: Predicted probablities


As a way of evaluating our classifier, we're going to recreate the dataset with every logical combination of input values. This will allow us to see how the predicted probability of admission increases/decreases across different variables. First we're going to generate the combinations using a helper function called cartesian (above).

We're going to use np.linspace to create a range of values for "gre" and "gpa". This creates a range of linearly spaced values from a specified min and maximum value--in our case just the min/max observed values.

In [64]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.
    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.
    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.
    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])
    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in range(1, arrays[0].size):  #use range instead of xrange for python3
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [65]:
# instead of generating all possible values of GRE and GPA, we're going
# to use an evenly spaced range of 10 values from the min to the max 
gres = np.linspace(data['gre'].min(), data['gre'].max(), 10)
print (gres)
# array([ 220.        ,  284.44444444,  348.88888889,  413.33333333,
#         477.77777778,  542.22222222,  606.66666667,  671.11111111,
#         735.55555556,  800.        ])
gpas = np.linspace(data['gpa'].min(), data['gpa'].max(), 10)
print (gpas)
# array([ 2.26      ,  2.45333333,  2.64666667,  2.84      ,  3.03333333,
#         3.22666667,  3.42      ,  3.61333333,  3.80666667,  4.        ])


# enumerate all possibilities
combos = pd.DataFrame(cartesian([gres, gpas, [1, 2, 3, 4], [1.]]))

[ 220.          284.44444444  348.88888889  413.33333333  477.77777778
  542.22222222  606.66666667  671.11111111  735.55555556  800.        ]
[ 2.26        2.45333333  2.64666667  2.84        3.03333333  3.22666667
  3.42        3.61333333  3.80666667  4.        ]


C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:42: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:44: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


#### 5.1 Recreate the dummy variables

In [ ]:
# recreate the dummy variables

# keep only what we need for making predictions


#### 5.2 Make predictions on the enumerated dataset

In [70]:
combos.head(3)

0     1    2    3
0  220.0  2.26  1.0  1.0
1  220.0  2.26  2.0  1.0
2  220.0  2.26  3.0  1.0

In [71]:
df_combos = combos.join(pd.get_dummies(combos[2],prefix='pres'))

# df.join(pd.get_dummies(df['prestige'],prefix='pres'))


In [85]:
df_combos.head(3)

0     1    2    3  pres_1.0  pres_2.0  pres_3.0  pres_4.0
0  220.0  2.26  1.0  1.0       1.0       0.0       0.0       0.0
1  220.0  2.26  2.0  1.0       0.0       1.0       0.0       0.0
2  220.0  2.26  3.0  1.0       0.0       0.0       1.0       0.0

In [86]:
#df_combos.drop(columns=['2','pres_4.0'])
df_combos = df_combos.drop([2,'pres_4.0'],axis=1)

In [87]:
df_combos.head(3)

0     1    3  pres_1.0  pres_2.0  pres_3.0
0  220.0  2.26  1.0       1.0       0.0       0.0
1  220.0  2.26  1.0       0.0       1.0       0.0
2  220.0  2.26  1.0       0.0       0.0       1.0

In [98]:
combos_cols = df_combos[[0, 1, 'pres_1.0', 'pres_2.0', 'pres_3.0']]
model.predict(combos_cols)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1,

#### 5.3 Interpret findings for the last 4 observations

Answer: prediction of admitting the fourth to last observation, but not the other 3.

## Bonus

Plot the probability of being admitted into graduate school, stratified by GPA and GRE score.